included:
  - Sources
  - Tests

excluded:
  - .build

opt_in_rules:
  - sorted_imports
  - duplicate_imports
  - file_types_order

disabled_rules:
  - trailing_comma
  - opening_brace

force_unwrapping:
  severity: error

implicitly_unwrapped_optional:
  severity: error

file_length:
  warning: 400
  error: 600

type_body_length:
  warning: 200
  error: 300

function_body_length:
  warning: 30
  error: 50

cyclomatic_complexity:
  warning: 10
  error: 15

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
